<?
// required: $columns, $form

foreach($columns as $name => $info) {
	switch($info['type']) {
		case 'hidden':
			echo $form[$name]->render();
			break;
		case 'checkbox':
			// this is modified recreation of the formo generation
			// doesn't support some select features right now
			
			// looks the id for the input checkbox is generated by appending the key of the option to the 
			
			echo "<p><b>{$info['label']}</b></p>";
			
			foreach($form[$name]->elements as $element => $type) {
				$el = $form[$name]->$element;
				echo "<p class='checkbox'><label for='{$el->id}'>".$form[$name]->$element->get(TRUE)." {$el->label}</label></p>";
			}
			
			break;
		case 'custom':
			echo $info['label'];
			break;
		default:
			echo "<p class='{$info['format']}'><label for=\"$name\">{$form[$name]->label}</label>".$form[$name]->render()."</p>";
			break;
	}
}
?>
